package com.ran.trello;

import com.ran.trello.Model.Entity.Project;
import com.ran.trello.Model.Entity.TaskCard;
import com.ran.trello.Model.Entity.UserP;
import com.ran.trello.Model.Entity.Wrapper;
import com.ran.trello.Model.Repository.ProjectRepository;
import com.ran.trello.Model.Repository.TaskCardRepository;
import com.ran.trello.Model.Repository.UserPRepository;
import com.ran.trello.Model.Repository.WrapperRepository;
import com.ran.trello.Service.UserPService;
import jakarta.persistence.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

import java.util.ArrayList;
import java.util.List;

@SpringBootApplication
public class PoecFilRougeKambanApplication {

	public static void main(String[] args) {
		ApplicationContext context = SpringApplication.run(PoecFilRougeKambanApplication.class, args);
		UserP u1 = new UserP("JeanValJean@gmail.com", "Jean", "Jean", "ValJean");
		UserP u2 = new UserP("BillyBob@gmail.com", "Billy", "Billy", "Bob");
		UserP u3 = new UserP("BobbyLarnak@gmail.com", "Bobby", "Bobby", "larnak");
		UserP u4 = new UserP("JohnnyLembrouille@gmail.com", "Johnny", "Johnny", "lembrouille");
		UserPRepository userRepository = context.getBean(UserPRepository.class);
		userRepository.save(u1);
		userRepository.save(u2);
		userRepository.save(u3);
		userRepository.save(u4);
		System.out.println("utilisateur crées");
		List<UserP> list = new ArrayList<>();
		list.add(u1);
		list.add(u2);
		list.add(u3);
		list.add(u4);
		System.out.println("list user crées");
		List<Wrapper> wrappers = new ArrayList<>();
		Project p1 = new Project("TrelloBis", "description de TrelloBis", "http://background", wrappers, list);
		Project p2 = new Project("TaskManager", "description de TaskManager", "http://background", wrappers, list);
		Project p3 = new Project("Trollolo", "description de Trollolo", "http://background", wrappers, list);
		ProjectRepository projectRepository = context.getBean(ProjectRepository.class);
		projectRepository.save(p1);
		projectRepository.save(p2);
		projectRepository.save(p3);
		System.out.println("project crées");
		List<TaskCard> listCard = new ArrayList<>();
		Wrapper w1 = new Wrapper("Wrappertitle", 0, listCard, p1.getId());
		Wrapper w2 = new Wrapper("Wrappertitle2", 1, listCard, p2.getId());
		Wrapper w3 = new Wrapper("Wrappertitle3", 2, listCard, p3.getId());
		Wrapper w4 = new Wrapper("Wrappertitle4", 3, listCard, p1.getId());
		Wrapper w5 = new Wrapper("Wrappertitle5", 3, listCard, p2.getId());
		Wrapper w6 = new Wrapper("Wrappertitle6", 4, listCard, p3.getId());
		Wrapper w7 = new Wrapper("Wrappertitle7", 5, listCard, p1.getId());

		List<Wrapper> wrappers2 = new ArrayList<>();
		wrappers2.add(w1);
		wrappers2.add(w2);
		wrappers2.add(w3);
		wrappers2.add(w4);
		wrappers2.add(w5);
		wrappers2.add(w6);
		wrappers2.add(w7);
		w1.setCards(listCard);
		w2.setCards(listCard);
		w3.setCards(listCard);
		w4.setCards(listCard);
		w5.setCards(listCard);
		w6.setCards(listCard);
		w7.setCards(listCard);
		WrapperRepository wrapperRepository = context.getBean(WrapperRepository.class);
		wrapperRepository.save(w1);
		wrapperRepository.save(w2);
		wrapperRepository.save(w3);
		wrapperRepository.save(w4);
		wrapperRepository.save(w5);
		wrapperRepository.save(w6);
		wrapperRepository.save(w7);
		System.out.println("wrapper crées");
		TaskCard t1 = new TaskCard("Task1", "task description", 0, w1.getId(), "status1");
		TaskCard t2 = new TaskCard("Task2", "task description", 1, w2.getId(), "status2");
		TaskCard t3 = new TaskCard("Task3", "task description", 2, w3.getId(), "status3");
		TaskCard t4 = new TaskCard("Task4", "task description", 3, w4.getId(), "status4");
		TaskCard t5 = new TaskCard("Task5", "task description", 4, w5.getId(), "status5");
		TaskCard t6 = new TaskCard("Task6", "task description", 5, w6.getId(), "status6");
		TaskCard t7 = new TaskCard("Task7", "task description", 6, w7.getId(), "status7");
		TaskCardRepository taskCardRepository = context.getBean(TaskCardRepository.class);
		taskCardRepository.save(t1);
		taskCardRepository.save(t2);
		taskCardRepository.save(t3);
		taskCardRepository.save(t4);
		taskCardRepository.save(t5);
		taskCardRepository.save(t6);
		taskCardRepository.save(t7);
		listCard.add(t1);
		listCard.add(t2);
		listCard.add(t3);
		listCard.add(t4);
		listCard.add(t5);
		listCard.add(t6);
		listCard.add(t7);
		w1.setCards(listCard);
		w2.setCards(listCard);
		w3.setCards(listCard);
		w4.setCards(listCard);
		w5.setCards(listCard);
		w6.setCards(listCard);
		w7.setCards(listCard);
		wrapperRepository.save(w1);
		wrapperRepository.save(w2);
		wrapperRepository.save(w3);
		wrapperRepository.save(w4);
		wrapperRepository.save(w5);
		wrapperRepository.save(w6);
		wrapperRepository.save(w7);
		wrappers = p1.getWrappers();
		wrappers.add(w1);
		wrappers.add(w2);
		wrappers.add(w3);
		wrappers.add(w4);
		wrappers.add(w5);
		wrappers.add(w6);
		wrappers.add(w7);
		p1.setWrappers(wrappers);

		projectRepository.save(p1);
		projectRepository.save(p2);
		projectRepository.save(p3);
		System.out.println("card crées");
	}
}
